export const LOGIN_REQUEST = "LOGIN_REQUEST" 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" 
export const LOGIN_FAIL = "LOGIN_FAIL" 

export const REGISTER_REQUEST = "REGISTER_REQUEST" 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS" 
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS" 
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST" 
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS" 
export const ALL_USERS_FAIL = "ALL_USERS_RESET"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST" 
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS" 
export const USER_DELETE_RESET = "USER_DELETE_RESET"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST" 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS" 
export const UPDATE_USER_RESET = "UPDATE_USER_RESET" 
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL" 

export const CLEAR_ERRORS = "CLEAR_ERRORS" 